#!/usr/bin/env python3

import nestedtext as nt
from inform import fatal, os_error

keymap = {}
source = 'test_cases.nt'
try:
    expressions = nt.load(source, top=list, keymap=keymap)
except OSError as e:
    fatal(os_error(e))
except nt.NestedTextError as e:
    e.terminate()

# evaluate expressions
for i, case in enumerate(expressions):
    try:
        evaluated = {}
        for key in ['expr', 'expected']:
            try:
                evaluated[key] = eval(case[key])
            except SyntaxError as e:
                raise nt.NestedTextDataError(
                    e, source=source, keys=(i, key), keymap=keymap,
                    offset=e.offset, zero_based_indices=False
                )
            except Exception as e:
                raise nt.NestedTextDataError(
                    e, source=source, keys=(i, key), keymap=keymap,
                    zero_based_indices=False
                )
        if evaluated['expr'] != evaluated['expected']:
            raise nt.NestedTextDataError(
                "test failed.", culprit=f"expr={case['expr']}",
                codicil=f"result={evaluated['expr']} ≠ expected={evaluated['expected']}",
                source=source, keys=(i, key), keymap=keymap, show_line=False,
                zero_based_indices=False
            )
    except nt.NestedTextDataError as e:
        e.report()
