#!/usr/bin/env sh

shopt -s globstar
rm -rf generated_settings
rm -rf .cache
rm -rf data.nt tests/data.nt

# the rest is common to all python directories
rm -f *.pyc *.pyo
rm -f .test*.sum expected result install.out .*.log
rm -rf build *.egg-info dist __pycache__ .eggs **/{__pycache__,*.pyc,*.pyo}
rm -rf .coverage .coverage-html htmlcov .tox
rm -rf .pytest_cache .cache dist .build quantiphy.egg.info
rm -rf tests/{htmlcov,.cache,.coverage,.pytest_cache}
rm -rf doc/.build
