#!/usr/bin/env python3
"""
Read a json file and convert it to udif.

usage:
    json-to-udif [<filename>]

If <filename> is not given, json input is taken from stdin and udif output is 
written to stdout.
"""

from docopt import docopt
from inform import display, fatal, os_error, render
from shlib import to_path
import json
import udif
import sys

cmdline = docopt(__doc__)
input_filename = cmdline['<filename>']

try:
    if input_filename:
        input_path = to_path(input_filename)
        json_content = input_path.read_text()
    else:
        json_content = sys.stdin.read()
    data = json.loads(json_content)
    udif_content = udif.dumps(data)
    if input_filename:
        output_path = input_path.with_suffix('.udif')
        output_path.write_text(udif_content)
    else:
        sys.stdout.write(udif_content)
except OSError as e:
    fatal(os_error(e))
except udif.Error as e:
    e.terminate()
except json.JSONDecodeError as e:
    fatal(e)
