#!/usr/bin/env python3
"""
Read a NestedText file and convert it to JSON.

usage:
    nestedtext-to-json [options] [<filename>]

options:
    -f, --force   force overwrite of output file

If <filename> is not given, NestedText input is taken from stdin and JSON output 
is written to stdout.
"""

from docopt import docopt
from inform import fatal, os_error
from pathlib import Path
import json
import nestedtext
import sys

cmdline = docopt(__doc__)
input_filename = cmdline['<filename>']

try:
    if input_filename:
        input_path = Path(input_filename)
        nestedtext_content = input_path.read_text()
    else:
        nestedtext_content = sys.stdin.read()
    data = nestedtext.loads(nestedtext_content, input_filename)
    json_content = json.dumps(data, indent=4)
    if input_filename:
        output_path = input_path.with_suffix('.json')
        if output_path.exists():
            if not cmdline['--force']:
                fatal('file exists, use -f to force over-write.', culprit=output_path)
        output_path.write_text(json_content)
    else:
        sys.stdout.write(json_content)
except OSError as e:
    fatal(os_error(e))
except nestedtext.NestedTextError as e:
    e.terminate()
