#!/usr/bin/env python3
"""
Read a udif file and convert it to json.

usage:
    udif-to-json [<filename>]

If <filename> is not given, udif input is taken from stdin and json output is 
written to stdout.
"""

from docopt import docopt
from inform import display, fatal, os_error, render
from shlib import to_path
import json
import udif
import sys

cmdline = docopt(__doc__)
input_filename = cmdline['<filename>']

try:
    if input_filename:
        input_path = to_path(input_filename)
        udif_content = input_path.read_text()
    else:
        udif_content = sys.stdin.read()
    data = udif.loads(udif_content, input_filename)
    json_content = json.dumps(data, indent=4)
    if input_filename:
        output_path = input_path.with_suffix('.json')
        output_path.write_text(json_content)
    else:
        sys.stdout.write(json_content)
except OSError as e:
    fatal(os_error(e))
except udif.Error as e:
    e.terminate()
