#!/usr/bin/env python3
from inform import codicil, display, fatal, full_stop, os_error
import nestedtext as nt

filename = "michael_jordan.nt"

def de_dup(key, state):
    if key not in state:
        state[key] = 1
    state[key] += 1
    return f"{key} #{state[key]}"

def format_key(key, parent_keys):
    return ', '.join(reversed(key.rsplit(maxsplit=1)))

try:
    # read contacts database
    data = nt.load(filename, 'dict', on_dup=de_dup, keymap=(keymap:={}))

    # display contact using deduplicated keys
    display("DE-DUPLICATED KEYS:")
    display(nt.dumps(data))

    # display contact using original keys
    display()
    display("ORIGINAL KEYS:")
    display(nt.dumps(data, keymap=keymap))

    # display contact using original keys
    display()
    display("MODIFIED KEYS:")
    display(nt.dumps(data, keymap=keymap, format_key=format_key))

except nt.NestedTextError as e:
    e.terminate()
except OSError as e:
    fatal(os_error(e))
