#!/usr/bin/env python3
"""
Display Contact Information

Usage:
    contact <name>
"""

from docopt import docopt
from inform import codicil, display, error, full_stop, indent, os_error, terminate
import nestedtext as nt
from voluptuous import Schema, Required, Any, MultipleInvalid
import re

contacts_file = "address.nt"

def normalize_key(key, parent_keys):
    if len(parent_keys) == 0:
        return key
    return ' '.join(key.lower().split())

def render_contact(data):
    text = nt.dumps(data, default=repr)
    return re.sub(r'^(\s*)[>:][ ]?(.*)$', r'\1\2', text, flags=re.M)

cmdline = docopt(__doc__)
name = cmdline['<name>']

try:
    # define structure of contacts database
    contacts_schema = Schema({
        str: {
            'position': str,
            'address': str,
            'phone': Required(Any({str:str},str)),
            'email': Required(Any({str:str},str)),
            'additional roles': Any(list,str),
        }
    })

    # read contacts database
    contacts = contacts_schema(
        nt.load(
            contacts_file,
            top = 'dict',
            normalize_key = normalize_key,
            keymap = (keymap:={})
        )
    )

    # display requested contact
    for fullname, contact_info in contacts.items():
        if name in fullname.lower():
            display(fullname)
            display(indent(render_contact(contact_info)))

except nt.NestedTextError as e:
    e.report()
except MultipleInvalid as e:
    for err in e.errors:
        kind = 'key' if 'key' in err.msg else 'value'
        keys = tuple(err.path)
        codicil = keymap[keys].as_line(kind) if keys in keymap else None
        error(
            full_stop(err.msg),
            culprit = (contacts_file, nt.join_keys(keys, keymap=keymap)),
            codicil = codicil
        )
except OSError as e:
    error(os_error(e))
terminate()
