name: NestedText
on: [push, pull_request]
jobs:
  check-bats-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]
        python-version: [3.6, 3.7, 3.8, 3.9]
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-node@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run:
          python -m pip install --upgrade pip
          pip install .
          pip install tox
      - name: Test NestedText
        run: tox

