name: NestedText
on: [push, pull_request]
jobs:
  check-bats-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.6", "3.x"]
      max-parallel: 6

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-node@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install coveralls
          pip install .
      - name: Run tests
        run: tox
      - name: Report test coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
        run: coveralls
